<a href="https://colab.research.google.com/github/Dhawaldwivedi/Bsc-3rd-sem-python-mmdu/blob/main/ai-ml-g2/numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy ??
- faster processing
- less memory consumption
- Support for multidimensional arrays and matrices
- integration with other libraries


In [73]:
!pip install numpy

In [ ]:
import numpy as np

In [74]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]

lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [75]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
type(arr)

numpy.ndarray

In [77]:
arr.ndim

2

In [78]:
arr.shape

(3, 3)

In [79]:
arr.size

9

In [80]:
# zeros and ones
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [86]:
np.random.random()

0.7219220992683658

In [90]:
np.random.random((2,3))

array([[0.17449848, 0.80894011, 0.87952103],
       [0.31751489, 0.50218278, 0.71028589]])

In [93]:
np.random.randint(1,6)

3

In [94]:
# arange function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [98]:
# linspace function
np.linspace(1,11,16) # number of elements between intervals

array([ 1.        ,  1.66666667,  2.33333333,  3.        ,  3.66666667,
        4.33333333,  5.        ,  5.66666667,  6.33333333,  7.        ,
        7.66666667,  8.33333333,  9.        ,  9.66666667, 10.33333333,
       11.        ])

In [99]:
# reshape
z = np.random.random((3,5))
z

array([[0.80857648, 0.91866892, 0.54638378, 0.67787332, 0.17682439],
       [0.83801057, 0.65822946, 0.55052762, 0.57496114, 0.90379773],
       [0.62794551, 0.20929435, 0.44503002, 0.77723671, 0.40036309]])

In [102]:
np.reshape(z,(5,3))


array([[0.80857648, 0.91866892, 0.54638378],
       [0.67787332, 0.17682439, 0.83801057],
       [0.65822946, 0.55052762, 0.57496114],
       [0.90379773, 0.62794551, 0.20929435],
       [0.44503002, 0.77723671, 0.40036309]])

In [103]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [6,7,8,5,4]])

In [104]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [106]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [108]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [109]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [111]:
# identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [112]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
int(arr.max())

9

In [114]:
int(arr.min())

1

In [115]:
int(arr.sum())

45

In [116]:
arr.max(axis=0) # column wise

array([7, 8, 9])

In [117]:
arr.max(axis=1)

array([3, 6, 9])

In [118]:
int(arr.trace())   # sum of diagonal elements

15

In [119]:
arr1 = np.array([[2,4,5],
                 [5,3,7],
                 [8,2,3]])
arr2 = np.array([[2,1,3],
                 [4,5,9],
                 [9,1,1]])

In [120]:
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [121]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [122]:
arr3 = arr1+arr2
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [124]:
int(arr3[2,1])

3

In [125]:
# sorting
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [126]:
np.sort(arr3)

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [127]:
arr4 = np.sort(arr3,axis=0)  # column wise
arr4

array([[ 4,  3,  4],
       [ 9,  5,  8],
       [17,  8, 16]])

In [128]:
arr5 = np.sort(arr3,axis=1)  # row wise

In [129]:
arr5

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [130]:
# merging arrays
# vstack , hstack
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [131]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [134]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3],
       [2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [135]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 4, 5, 2, 1, 3],
       [5, 3, 7, 4, 5, 9],
       [8, 2, 3, 9, 1, 1]])

In [139]:
# vsplit , hsplit
np.vsplit(arr3,2)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]])]

In [140]:
np.hsplit(arr4,2)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]])]

Normalization

In [141]:
# 2,3,44,876,2,9,4-233
data = np.array([1,2,39,450,9])


In [143]:
# max , min method
max_val = np.max(data)
min_val = np.min(data)
print(max_val)
print(min_val)

450
1


In [144]:
normalize_array = (data-min_val)/(max_val-min_val)
normalize_array

array([0.        , 0.00222717, 0.08463252, 1.        , 0.01781737])

In [ ]:
# z score normalization

# mean - average
# median - middle value for a sorted data
# mode - most frequent value

In [145]:
mean_val = np.mean(data)
std_val = np.std(data)

In [146]:
norm_array = (data-mean_val)/std_val
norm_array

array([-0.56541558, -0.55971582, -0.34882493,  1.99377388, -0.51981755])