<a href="https://colab.research.google.com/github/Dhawaldwivedi/Bsc-3rd-sem-python-mmdu/blob/main/ai-ml-g3/numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy ??
- faster processing
- less memory consumption
- Support for multidimensional arrays and matrices
- integration with other libraries


In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]

lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(3, 3)

In [8]:
arr.size

9

In [9]:
# zeros and ones
z = np.zeros((3,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
o = np.ones((6,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.random.random()

0.6205289808212588

In [15]:
np.random.random((2,2))

array([[0.40868976, 0.49626798],
       [0.14638339, 0.07102198]])

In [16]:
np.random.randint(1,6)

2

In [17]:
# arange function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [24]:
# linspace function
np.linspace(1,11,16)

array([ 1.        ,  1.66666667,  2.33333333,  3.        ,  3.66666667,
        4.33333333,  5.        ,  5.66666667,  6.33333333,  7.        ,
        7.66666667,  8.33333333,  9.        ,  9.66666667, 10.33333333,
       11.        ])

In [26]:
# reshape
z = np.random.random((3,5))
z

array([[0.54386307, 0.87047428, 0.25957702, 0.31494286, 0.39563335],
       [0.44826093, 0.839837  , 0.30508728, 0.024754  , 0.31910605],
       [0.92510047, 0.36738048, 0.7951722 , 0.53603166, 0.72788021]])

In [30]:
np.reshape(z,(5,3))


array([[0.54386307, 0.87047428, 0.25957702],
       [0.31494286, 0.39563335, 0.44826093],
       [0.839837  , 0.30508728, 0.024754  ],
       [0.31910605, 0.92510047, 0.36738048],
       [0.7951722 , 0.53603166, 0.72788021]])

In [32]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [6,7,8,5,4]])

In [ ]:
np.reshape(a,(5,3))

In [ ]:
np.reshape(a,(4,4))

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [35]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [37]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [38]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [39]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
int(arr.max())

9

In [42]:
int(arr.min())

1

In [43]:
int(arr.sum())

45

In [45]:
arr.max(axis=0) # column wise

array([7, 8, 9])

In [46]:
arr.max(axis=1)

array([3, 6, 9])

In [44]:
int(arr.trace())   # sum of diagonal elements

15

In [47]:
arr1 = np.array([[2,4,5],
                 [5,3,7],
                 [8,2,3]])
arr2 = np.array([[2,1,3],
                 [4,5,9],
                 [9,1,1]])

In [48]:
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [49]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [50]:
arr3 = arr1+arr2
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [52]:
int(arr3[2,1])

3

In [ ]:
arr3[:,:2]

In [53]:
# sorting
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [54]:
np.sort(arr3)

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [55]:
arr4 = np.sort(arr3,axis=0)  # column wise
arr4

array([[ 4,  3,  4],
       [ 9,  5,  8],
       [17,  8, 16]])

In [ ]:
arr5 = np.sort(arr3,axis=1)  # row wise

In [ ]:
arr5

In [56]:
# merging arrays
# vstack , hstack
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [57]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [ ]:
arr5

In [58]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3],
       [2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [59]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 4, 5, 2, 1, 3],
       [5, 3, 7, 4, 5, 9],
       [8, 2, 3, 9, 1, 1]])

In [61]:
# vsplit , hsplit
np.vsplit(arr3,3)

[array([[2, 4, 5],
        [5, 3, 7]]),
 array([[8, 2, 3],
        [2, 1, 3]]),
 array([[4, 5, 9],
        [9, 1, 1]])]

In [62]:
np.hsplit(arr4,2)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]])]

Normalization

In [ ]:
# 2,3,44,876,2,9,4-233
data = np.array([1,2,39,450,9])


In [ ]:
# max , min method
max_val = np.max(data)
min_val = np.min(data)

In [ ]:
normalize_array = (data-min_val)/(max_val-min_val)
normalize_array

In [ ]:
# z score normalization

# mean - average
# median - middle value for a sorted data
# mode - most frequent value

In [ ]:
mean_val = np.mean(data)
std_val = np.std(data)

In [ ]:
norm_array = (data-mean_val)/std_val
norm_array