<a href="https://colab.research.google.com/github/Dhawaldwivedi/Bsc-3rd-sem-python-mmdu/blob/main/bsc-pds/numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy ??
- faster processing
- less memory consumption
- Support for multidimensional arrays and matrices
- integration with other libraries


In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]

lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

2

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
# zeros and ones
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.random.random()

0.7991531056869667

In [21]:
np.random.random((3,4))

array([[0.71692288, 0.78494289, 0.51981646, 0.48793835],
       [0.05241223, 0.66843552, 0.20747431, 0.50446222],
       [0.10632911, 0.7856486 , 0.49751883, 0.82654259]])

In [26]:
np.random.randint(1,6)

3

In [27]:
# arange function
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [30]:
# linspace function
np.linspace(1,11,12)

array([ 1.        ,  1.90909091,  2.81818182,  3.72727273,  4.63636364,
        5.54545455,  6.45454545,  7.36363636,  8.27272727,  9.18181818,
       10.09090909, 11.        ])

In [32]:
# reshape
z = np.random.random((3,5))
z

array([[0.87498228, 0.32617953, 0.06420635, 0.11439216, 0.11356395],
       [0.14747918, 0.17296962, 0.81543587, 0.23236749, 0.40595627],
       [0.60236401, 0.3746919 , 0.25524617, 0.61338391, 0.28252271]])

In [35]:
np.reshape(z,(5,3))


array([[0.87498228, 0.32617953, 0.06420635],
       [0.11439216, 0.11356395, 0.14747918],
       [0.17296962, 0.81543587, 0.23236749],
       [0.40595627, 0.60236401, 0.3746919 ],
       [0.25524617, 0.61338391, 0.28252271]])

In [36]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [6,7,8,5,4]])

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [39]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [42]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [43]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
int(arr.max())

9

In [46]:
int(arr.min())

1

In [47]:
int(arr.sum())

45

In [48]:
arr.max(axis=0) # column wise

array([7, 8, 9])

In [49]:
arr.max(axis=1)

array([3, 6, 9])

In [50]:
int(arr.trace())   # sum of diagonal elements

15

In [51]:
arr1 = np.array([[2,4,5],
                 [5,3,7],
                 [8,2,3]])
arr2 = np.array([[2,1,3],
                 [4,5,9],
                 [9,1,1]])

In [52]:
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [53]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [54]:
arr3 = arr1+arr2
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [56]:
int(arr3[0,2])

8

In [57]:
# sorting
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [58]:
np.sort(arr3)

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [59]:
arr4 = np.sort(arr3,axis=0)  # column wise
arr4

array([[ 4,  3,  4],
       [ 9,  5,  8],
       [17,  8, 16]])

In [60]:
arr5 = np.sort(arr3,axis=1)  # row wise

In [61]:
arr5

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [62]:
# merging arrays
# vstack , hstack
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [63]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [66]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3],
       [2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [67]:
arr4 = np.hstack((arr1,arr2))
arr4

array([[2, 4, 5, 2, 1, 3],
       [5, 3, 7, 4, 5, 9],
       [8, 2, 3, 9, 1, 1]])

In [71]:
# vsplit , hsplit
np.vsplit(arr3,2)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]])]

In [72]:
np.hsplit(arr4,2)

[array([[2, 4, 5],
        [5, 3, 7],
        [8, 2, 3]]),
 array([[2, 1, 3],
        [4, 5, 9],
        [9, 1, 1]])]

Normalization

In [ ]:
# 2,3,44,876,2,9,4-233
data = np.array([1,2,39,450,9])


In [ ]:
# max , min method
max_val = np.max(data)
min_val = np.min(data)

In [ ]:
normalize_array = (data-min_val)/(max_val-min_val)
normalize_array

In [ ]:
# z score normalization

# mean - average
# median - middle value for a sorted data
# mode - most frequent value

In [ ]:
mean_val = np.mean(data)
std_val = np.std(data)

In [ ]:
norm_array = (data-mean_val)/std_val
norm_array