<a href="https://colab.research.google.com/github/Dhawaldwivedi/Bsc-3rd-sem-python-mmdu/blob/main/ai-ml-g1/numpy_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy - statistical analysis
# pandas - data manipulation
# matplotlib - data visualization
# seaborn - data visualization

Why to use numpy ??
- faster processing
- less memory consumption
- Support for multidimensional arrays and matrices
- integration with other libraries


In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]

lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(3, 3)

In [8]:
arr.size

9

In [9]:
# zeros and ones
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
int(np.random.random()*100)

52

In [44]:
np.random.random((2,3))

array([[0.4915612 , 0.20456752, 0.07730101],
       [0.09198368, 0.76307408, 0.27397529]])

In [38]:
np.random.randint(1,6)

3

In [46]:
# arange function
np.arange(1,14)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [47]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [49]:
# linspace function
np.linspace(1,11,10) # number of elements between intervals

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [50]:
# reshape
z = np.random.random((3,5))
z

array([[0.81080393, 0.67742873, 0.59367874, 0.34645922, 0.13812599],
       [0.17083826, 0.05992079, 0.68512693, 0.33973388, 0.98740233],
       [0.25557535, 0.072603  , 0.29686683, 0.35305614, 0.68533866]])

In [54]:
np.reshape(z,(5,3))


array([[0.81080393, 0.67742873, 0.59367874],
       [0.34645922, 0.13812599, 0.17083826],
       [0.05992079, 0.68512693, 0.33973388],
       [0.98740233, 0.25557535, 0.072603  ],
       [0.29686683, 0.35305614, 0.68533866]])

In [55]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3,4,5],
             [4,5,6,7,8],
             [6,7,8,5,4]])

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [58]:
arr-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [60]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [61]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [63]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
int(arr.max())

9

In [66]:
int(arr.min())

1

In [67]:
int(arr.sum())

45

In [68]:
arr.max(axis=0) # column wise

array([7, 8, 9])

In [69]:
arr.max(axis=1)

array([3, 6, 9])

In [70]:
int(arr.trace())   # sum of diagonal elements

15

In [71]:
arr1 = np.array([[2,4,5],
                 [5,3,7],
                 [8,2,3]])
arr2 = np.array([[2,1,3],
                 [4,5,9],
                 [9,1,1]])

In [72]:
arr1

array([[2, 4, 5],
       [5, 3, 7],
       [8, 2, 3]])

In [73]:
arr2

array([[2, 1, 3],
       [4, 5, 9],
       [9, 1, 1]])

In [74]:
arr3 = arr1+arr2
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [76]:
int(arr3[1,2])

16

In [77]:
# sorting
arr3

array([[ 4,  5,  8],
       [ 9,  8, 16],
       [17,  3,  4]])

In [78]:
np.sort(arr3)

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [79]:
arr4 = np.sort(arr3,axis=0)  # column wise
arr4

array([[ 4,  3,  4],
       [ 9,  5,  8],
       [17,  8, 16]])

In [80]:
arr5 = np.sort(arr3,axis=1)  # row wise

In [81]:
arr5

array([[ 4,  5,  8],
       [ 8,  9, 16],
       [ 3,  4, 17]])

In [ ]:
# merging arrays
# vstack , hstack
arr1

In [ ]:
arr2

In [ ]:
arr3 = np.vstack((arr1,arr2))
arr3

In [ ]:
arr4 = np.hstack((arr1,arr2))
arr4

In [ ]:
# vsplit , hsplit
np.vsplit(arr3,2)

In [ ]:
np.hsplit(arr4,2)

Normalization

In [ ]:
# 2,3,44,876,2,9,4-233
data = np.array([1,2,39,450,9])


In [ ]:
# max , min method
max_val = np.max(data)
min_val = np.min(data)
print(max_val)
print(min_val)

In [ ]:
normalize_array = (data-min_val)/(max_val-min_val)
normalize_array

In [ ]:
# z score normalization

# mean - average
# median - middle value for a sorted data
# mode - most frequent value

In [ ]:
mean_val = np.mean(data)
std_val = np.std(data)

In [ ]:
norm_array = (data-mean_val)/std_val
norm_array